### ISSUE TITLE
Showing list of files that are rsynced

### ISSUE THREAD

**Issue by PhilippSoehnlein** [wki/Provision-DSL#1]
It would be great if there would be a possibility to get the list of (to be) synced files in the output of ``provision.pl``.
It's probably a good idea to print the additional output only in a "more verbose" mode which can be triggered by something like ``-vv``. I recommend <a href="https://metacpan.org/pod/Getopt::Long::Descriptive">Getopt::Long::Descriptive</a> as getopt lib, it can handle multiple flags.

**Comment by wki** [comment]
Hi,

actually I already had the foundation for all that but did not remember -- sorry for that, too much C# during the last year... 

Currently the commandline handling is done with Getopt::Long, and the verbose switch already is marked as an incrementable integer value. Verbose mode 2 is more verbose and verbose mode 3 equals debug mode. Some Entities already use the mode 2 logging for providing additional info.

I added a file list to get copied/deleted in a real executed rsync command. Unfortunately, the order might confuse a user. As the rsync command is called in order to determine if something has to be done, its output appears in front of the actual decision to do or not to do something. An example is quoted below. Let's talk about some possibilities we have for improving if this would be too confusing.

```
$ PERL5LIB=lib bin/provision.pl -c examples/box.conf -vv -n
[...]
Dir('/web/data') ............................................. current - OK
copying dir1/file2.txt
Dir('/web/data/www.mysite.de') .................... outdated - would change
```

**Comment by wki** [comment]
fixed
